#!/bin/bash
# Pings an IP address passed as argument to check network connectivity
# Check if an argument was provided
if [ $# -eq 0 ]; then
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
	# Ping the IP address 5 times
	ping -c 5 "$1"
fi
